backend:
  name: github
  repo: KristianBerg/eira-webpage
  branch: main
  auth_type: pkce
  app_id: Ov23liNvnUnpYjaMpmFi

media_folder: public/images/artworks
public_folder: /images/artworks

collections:
  - name: artworks
    label: Artworks
    files:
      - name: artworks
        label: All Artworks
        file: public/content/artworks.json
        fields:
          - label: Artworks
            name: artworks
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Price, name: price, widget: string, required: false }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
